# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### Turi buti klaida 404 (empNo = 999999)

GET http://localhost:8080/web/rest/employee/999999

###

GET http://localhost:8080/web/rest/employee/100000

###

GET http://localhost:8080/web/rest/employee/100000?salaries=true

###

POST http://localhost:8080/web/rest/employee
Content-Type: application/json

{
  "empNo": 6,
  "firstName": "Petriukas", "lastName": "Petraitis", "gender": "MALE",
  "birthDate": "1999-12-31", "hireDate": "2018-01-01"
}

### Turi buti 400 klaida, nes uzklausoje nurodytas empNo = 1, o json "empNo": 2

PUT http://localhost:8080/web/rest/employee/1
Content-Type: application/json

{
  "empNo": 2,
  "firstName": "Petra", "lastName": "Petraitė", "gender": "FEMALE",
  "birthDate": "1999-12-31", "hireDate": "2018-01-01"
}

### Turi buti klaida: lt.bit.java2.db.DBUtils$DBException: Entity not found

PUT http://localhost:8080/web/rest/employee/999999
Content-Type: application/json

{
  "firstName": "Petra", "lastName": "Petraitė", "gender": "FEMALE",
  "birthDate": "1999-12-31", "hireDate": "2018-01-01"
}

###

PUT http://localhost:8080/web/rest/employee/7
Content-Type: application/json

{
  "firstName": "Petra", "lastName": "Petraitė", "gender": "FEMALE",
  "birthDate": "1999-12-31", "hireDate": "2018-01-01"
}

###

